#!/bin/bash

# Leemos valores iniciales
cpu_before=($(grep '^cpu ' /proc/stat))
idle_before=${cpu_before[4]}
total_before=0
for val in "${cpu_before[@]:1}"; do
    total_before=$((total_before + val))
done

# Esperamos 1 segundo
sleep 1

# Leemos valores de nuevo
cpu_after=($(grep '^cpu ' /proc/stat))
idle_after=${cpu_after[4]}
total_after=0
for val in "${cpu_after[@]:1}"; do
    total_after=$((total_after + val))
done

# Calculamos diferencias
delta_idle=$((idle_after - idle_before))
delta_total=$((total_after - total_before))
delta_usage=$((100 * (delta_total - delta_idle) / delta_total))

if [ "$delta_usage" -lt 10 ]; then
    echo "0${delta_usage}%"
elif [ "$delta_usage" -eq 100 ]; then
    echo "Max"
else
    echo "${delta_usage}%"
fi

